# Generated by Django 2.2.2 on 2019-09-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bus_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='dest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='dest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
